# Numpy Array For ML and Data science [Sk Miraj]

In [1]:
import numpy as np

In [2]:
print('Python Activated')

Python Activated


**Numpy array**

In [3]:
x = np.array([1,2,3,4,5,6,7])
y = np.array([11,22,41,51,2,4,9])

In [4]:
x

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
y

array([11, 22, 41, 51,  2,  4,  9])

In [6]:
print(x+y)
print(type(x+y))
print(x*y)

[12 24 44 55  7 10 16]
<class 'numpy.ndarray'>
[ 11  44 123 204  10  24  63]


In [7]:
type(x)

numpy.ndarray

**Numpy array Data type**

In [8]:
arr = np.array([7,88,9,6],np.int8)
arr

array([ 7, 88,  9,  6], dtype=int8)

In [9]:
arr[0]

7

In [10]:
arr1 = np.array([7,88,9,6],np.int64)
arr1

array([ 7, 88,  9,  6])

In [11]:
arr1[1]

88

In [12]:
arr2 = np.array([7.3,88.7,9.4,6.9],np.float32)
arr2

array([ 7.3, 88.7,  9.4,  6.9], dtype=float32)

In [13]:
arr2[0]

7.3

**Numpy array details**

In [14]:
a = np.array([7,88,9,6],np.int8)

In [15]:
print('No of nows and coloumn is 1D: ')
a.shape

No of nows and coloumn is 1D: 


(4,)

In [16]:
b = np.array([[7,88,9,6],[8,9,7,31],[88,47,51,64]],np.int8)
print('No of nows and coloumn is 2D: ')
b.shape

No of nows and coloumn is 2D: 


(3, 4)

In [17]:
print('Array data type is : ')
print(a.dtype)
print('\nArray data type is : ')
print(b.dtype)

Array data type is : 
int8

Array data type is : 
int8


In [18]:
print('Array size is : ')
print(a.size)
print('\nArray size is : ')
print(b.size)

Array size is : 
4

Array size is : 
12


**Value exchange**

In [19]:
arr5 = np.array([7,8,9,3,6])
arr5

array([7, 8, 9, 3, 6])

In [20]:
print('Array 0 index is : ')
arr5[0]

Array 0 index is : 


7

In [21]:
print('Before Exchange value is :\n')
print(arr5)
print('After Exchange value is :\n')
arr5[0]=10
print(arr5)

Before Exchange value is :

[7 8 9 3 6]
After Exchange value is :

[10  8  9  3  6]


In [22]:
print('All value exchange between range 0 to 5 is using split :\n')
arr5[0:3]=5
print(arr5)

All value exchange between range 0 to 5 is using split :

[5 5 5 3 6]


**Numpy Array creation methods :**

1. Conversion from other Python structures (i.e. lists and tuples)

2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

3. Replicating, joining, or mutating existing arrays

4. Reading arrays from disk, either from standard or custom formats

5. Creating arrays from raw bytes through the use of strings or buffers

6. Use of special library functions (e.g., random

In [23]:
print('1. Conversion from other Python structures (i.e. lists and tuples)\n')
xl = [12,24,57,84,61,34]
xt = (1,8,7,9,3,10)
xs = {34,51,48,75,68}

print('\nList array :')
listarray = np.array(xl)
print(listarray)

print('\nTuple array :')
Tuplearray = np.array(xt)
print(Tuplearray)

print('\nSet array :')
Setarray = np.array(xs)
print(Setarray)

1. Conversion from other Python structures (i.e. lists and tuples)


List array :
[12 24 57 84 61 34]

Tuple array :
[ 1  8  7  9  3 10]

Set array :
{48, 34, 51, 68, 75}


In [24]:
Tuplearray[0]=56
print(Tuplearray)

listarray[0]=91
print(listarray)

[56  8  7  9  3 10]
[91 24 57 84 61 34]


In [25]:
print ('2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.) :\n')

print('Zros of array :\n')
zeros = np.zeros((3,4))
print(zeros)

print('\nOnes of array :\n')
ones = np.ones((3,4))
print(ones)

print('\nRange of array :\n')
rangearr = np.arange(10)
print(rangearr)

print('\nLinier space of array :\n')
linier = np.linspace(1,50,25)
print(linier)

print('\nRandom Empty of array :\n')
empty = np.empty((4,6))
print(empty)

print('\nRandom Empty_like of array :\n')
empty_like = np.empty_like(linier) # or pass row and coloumn its copy initality of any matrix
print(empty_like)

print('\nIdentity of array :\n')
Identity = np.identity(10)
print(Identity)
print('\n Row X Coloumn of Identity is : ',Identity.shape,'\n')


print('\nEye Empty of array :\n')
eye = np.eye(5,10)
print(eye)

2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.) :

Zros of array :

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones of array :

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Range of array :

[0 1 2 3 4 5 6 7 8 9]

Linier space of array :

[ 1.          3.04166667  5.08333333  7.125       9.16666667 11.20833333
 13.25       15.29166667 17.33333333 19.375      21.41666667 23.45833333
 25.5        27.54166667 29.58333333 31.625      33.66666667 35.70833333
 37.75       39.79166667 41.83333333 43.875      45.91666667 47.95833333
 50.        ]

Random Empty of array :

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Random Empty_like of array :

[ 1.          3.04166667  5.08333333  7.125       9.16666667 11.20833333
 13.25       15.29166667 17.33333333 19.375      21.41666667 23.45833333
 25.5        27.54166667 29.58333333 31.625      33.66666667 35.70833333
 37.75       39.79166667 41.83333333 43.875      45.9166666

**Importent functions of Numpy Array :-**

In [26]:
ar = np.arange(100)
print(ar)

print('\nDivide array into equal size blocks :\n')
ar.reshape(4,25)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Divide array into equal size blocks :



array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
print('\nTo combine array into a single 1D array :\n')
ar.ravel()


To combine array into a single 1D array :



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

**Numpy array methods and attributes :-**

In [28]:
x = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(x)
b = np.array(x)
print(x)

print('\nSum of y axis (coloumn) :\n')
print(a.sum(axis=0))

print('\nSum of x axis (row) :\n')
print(a.sum(axis=1))

print('\nTranspose of NDarray is :\n')
print(a.T)

print('\nNDarray Traverse is :\n')
for i in a:
    print(i)
    
print('\nNDarray itaration is :\n')
for i in a.flat:
    print(i)
    
print('\nDiamension of NDarray is :\n')
print(a.ndim)

print('\nNDarray size or total element is :\n')
print(a.size)

print('\nNDarray memory size is :\n')
print(a.nbytes,'byte')

print('\nMAx aurgument in X axis :\n')
print(a.argmax(axis=1))

print('\nMAx aurgument in Y axis :\n')
print(a.argmax(axis=0))

print('\nMin aurgument in X axis :\n')
print(a.argmin(axis=1))

print('\nMin aurgument in Y axis :\n')
print(a.argmin(axis=0))

print('\nArgument sort of NDarray :\n')
print(a.argsort())

print('\nMean of NDarray is :\n')
print(a.mean())

print('\nMedian of NDarray :\n')
print(np.median(a))

print('\nSum of NDarray : \n')
print(a+b)

print('\nMultiplay of NDarray : \n')
print(a*b)

print('\nSqureroot of NDarray : \n')
print(np.sqrt(a))

print('\nCuberoot of NDarray : \n')
print(np.cbrt(a))

print('\nSum of all elements  : \n')
print(a.sum())

print('\nMax of all elements  : \n')
print(a.max())

print('\nMin of all elements  : \n')
print(a.min())

print('\nNDarray condition ary>5 : \n')
ary = np.array([[1,2,3],[4,5,6],[7,1,0]])
print(ary)
print(np.where(ary>5))


print('\nDiagonal  of NDarray : \n')
print(a.diagonal())

print('\nNumpy array to python list :\n')
print(type(a))
print(a)
x = a.tolist()
print('\n',type(x))
print(x)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Sum of y axis (coloumn) :

[12 15 18]

Sum of x axis (row) :

[ 6 15 24]

Transpose of NDarray is :

[[1 4 7]
 [2 5 8]
 [3 6 9]]

NDarray Traverse is :

[1 2 3]
[4 5 6]
[7 8 9]

NDarray itaration is :

1
2
3
4
5
6
7
8
9

Diamension of NDarray is :

2

NDarray size or total element is :

9

NDarray memory size is :

72 byte

MAx aurgument in X axis :

[2 2 2]

MAx aurgument in Y axis :

[2 2 2]

Min aurgument in X axis :

[0 0 0]

Min aurgument in Y axis :

[0 0 0]

Argument sort of NDarray :

[[0 1 2]
 [0 1 2]
 [0 1 2]]

Mean of NDarray is :

5.0

Median of NDarray :

5.0

Sum of NDarray : 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Multiplay of NDarray : 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Squreroot of NDarray : 

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

Cuberoot of NDarray : 

[[1.         1.25992105 1.44224957]
 [1.58740105 1.70997595 1.81712059]
 [1.91293118 2.         2.08008382

In [29]:
x = [13,45,6,78,0,74]
arr=np.array(x)
print(arr)

print('Argmax X',' Argmin X',' Argsort [index]','\t Mean ')
print(' ',arr.argmax(axis=0),' \t',arr.argmin(axis=0),' \t',arr.argsort(axis=0),' \t',arr.mean())

[13 45  6 78  0 74]
Argmax X  Argmin X  Argsort [index] 	 Mean 
  3  	 4  	 [4 2 0 1 5 3]  	 36.0


In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print('Dotproduct is : ',np.dot(a,b))

Dotproduct is :  32


In [31]:
x = np.array([1,-3,5,-7])
print('Absolute value is :',np.absolute(x))

Absolute value is : [1 3 5 7]


In [32]:
y = np.array([2.0,1.0j,1+1j,])
print('Angle of NDarray complex number [Radians]: ',np.angle(y))

Angle of NDarray complex number [Radians]:  [0.         1.57079633 0.78539816]


In [33]:
print('Non zero in NDarry :')
zero = np.zeros((3,3))
zero[1,1]=1
print(zero)
print(np.count_nonzero(zero))

Non zero in NDarry :
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
1


In [34]:
print('Non zero index is :')
print(np.nonzero(zero))

Non zero index is :
(array([1]), array([1]))


**Numpy with Random :-**

In [37]:
print('Random valuus between 0 to 1 NDarray 1D :')
arr = np.random.rand(3)
print(arr,type(arr))

print('\nRandom valuus between 0 to 1 NDarray 2D :')
arr = np.random.rand(3,3)
print(arr,type(arr))

print('\nRandom valuus randint NDarray :')
arr = np.random.randint(0,10,5)
print(arr,type(arr))

print('\nRandom valuus between n to m NDarray :')
arr = np.random.sample(size=(3,3))
print(arr,type(arr))

print('\nRandom valuus between choice NDarray :')
arr = np.random.choice(13, 30)
print(arr,type(arr))

Random valuus between 0 to 1 NDarray 1D :
[0.46079734 0.20053821 0.28038252] <class 'numpy.ndarray'>

Random valuus between 0 to 1 NDarray 2D :
[[0.39532625 0.47177508 0.05554833]
 [0.84264942 0.20158213 0.39933174]
 [0.2985259  0.9478043  0.15965911]] <class 'numpy.ndarray'>

Random valuus randint NDarray :
[9 3 8 3 9] <class 'numpy.ndarray'>

Random valuus between n to m NDarray :
[[0.99686481 0.61719675 0.25213915]
 [0.59520155 0.96502253 0.26808828]
 [0.67635637 0.16238437 0.63988968]] <class 'numpy.ndarray'>

Random valuus between choice NDarray :
[ 4 11  8  6  9 10 12  3  4 12  4  9  9 10  5 10 10 12  9  4  1  4 12  3
  1  3 10  4  2 11] <class 'numpy.ndarray'>
